create database ARTICULOABM
go
use ARTICULOABM
GO
create table MARCAS(
ID INT NOT NULL PRIMARY KEY,
CODIGO VARCHAR(16) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
)
GO
create table LINEAS(
ID INT NOT NULL PRIMARY KEY,
CODIGO VARCHAR(16) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
)
GO
create table ARTICULOS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CODIGO VARCHAR(16) NOT NULL,
MARCAID INT NOT NULL FOREIGN KEY REFERENCES MARCAS(ID),
LINEAID INT NOT NULL FOREIGN KEY REFERENCES LINEAS(ID),
DESCRIPCION VARCHAR(1000) NOT NULL,
PRECIO FLOAT NOT NULL,
IMAGEN VARCHAR(1000)
)